use serde::Serialize;

use crate::benchmark::BenchmarkResult;
use crate::metrics::RunMetrics;

#[derive(Debug, Serialize)]
pub struct Report {
    pub run_id: String,
    pub harness_name: String,
    pub benchmark_name: String,
    pub metrics: RunMetrics,
    pub results: Vec<BenchmarkResult>,
}

impl Report {
    pub fn to_markdown(&self) -> String {
        let mut md = format!(
            "# AgentBench Report\n\n**Run ID:** {}\n**Harness:** {}\n**Benchmark:** {}\n\n",
            self.run_id, self.harness_name, self.benchmark_name
        );

        md.push_str("## Summary\n\n");
        md.push_str(&format!(
            "- **Total Tasks:** {}\n",
            self.metrics.total_tasks
        ));
        md.push_str(&format!("- **Passed:** {}\n", self.metrics.passed_tasks));
        md.push_str(&format!("- **Failed:** {}\n", self.metrics.failed_tasks));
        md.push_str(&format!(
            "- **Pass Rate:** {:.1}%\n",
            self.metrics.pass_rate * 100.0
        ));
        md.push_str(&format!(
            "- **Avg Latency:** {:.0}ms\n",
            self.metrics.avg_latency_ms
        ));
        md.push_str(&format!(
            "- **Total Tokens:** {}\n",
            self.metrics.total_tokens_input + self.metrics.total_tokens_output
        ));
        md.push('\n');

        md.push_str("## Results\n\n");
        md.push_str("| Task | Status | Score | Latency | Input | Output |\n");
        md.push_str("|------|--------|-------|---------|-------|--------|\n");

        for r in &self.results {
            let status = if r.passed { "✅ PASS" } else { "❌ FAIL" };
            md.push_str(&format!(
                "| {} | {} | {:.2} | {}ms | {} | {} |\n",
                r.task_id,
                status,
                r.score,
                r.response.latency_ms,
                r.response.tokens_input,
                r.response.tokens_output
            ));
        }

        md
    }

    pub fn to_json(&self) -> String {
        serde_json::to_string_pretty(self).unwrap_or_default()
    }

    pub fn to_html(&self) -> String {
        let mut rows = String::new();
        for r in &self.results {
            let (status, class) = if r.passed {
                ("PASS", "pass")
            } else {
                ("FAIL", "fail")
            };
            rows.push_str(&format!(
                "<tr class=\"{}\"><td>{}</td><td>{}</td><td>{:.2}</td><td>{}ms</td><td>{}</td><td>{}</td></tr>\n",
                class,
                html_escape(&r.task_id),
                status,
                r.score,
                r.response.latency_ms,
                r.response.tokens_input,
                r.response.tokens_output
            ));
        }
        format!(
            r#"<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>AgentBench Report — {}</title>
<style>
body {{ background: #0f0225; color: #e0d7ff; font-family: 'Courier New', monospace; margin: 2em; }}
h1 {{ color: #ff7edb; text-shadow: 0 0 12px #ff7edb; }}
h2 {{ color: #36f9f6; }}
.summary li {{ margin: 0.2em 0; }}
table {{ border-collapse: collapse; width: 100%; margin-top: 1em; }}
th, td {{ border: 1px solid #5a3a8a; padding: 6px 10px; text-align: left; }}
th {{ background: #2b1a4a; color: #36f9f6; }}
tr.pass td {{ color: #7ee787; }}
tr.fail td {{ color: #ff6b6b; }}
.footer {{ margin-top: 2em; color: #8a7aa8; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>AgentBench Report</h1>
<ul class="summary">
<li>Run ID: {}</li>
<li>Harness: {}</li>
<li>Benchmark: {}</li>
</ul>
<h2>Summary</h2>
<ul class="summary">
<li>Total Tasks: {}</li>
<li>Passed: {}</li>
<li>Failed: {}</li>
<li>Pass Rate: {:.1}%</li>
<li>Avg Latency: {:.0}ms</li>
<li>Total Tokens: {}</li>
<li>Total Cost: ${:.4}</li>
</ul>
<h2>Results</h2>
<table>
<tr><th>Task</th><th>Status</th><th>Score</th><th>Latency</th><th>Input Tok</th><th>Output Tok</th></tr>
{}
</table>
<p class="footer">Generated by AgentBench — synthalorian/agentbench</p>
</body>
</html>"#,
            self.run_id,
            self.run_id,
            html_escape(&self.harness_name),
            html_escape(&self.benchmark_name),
            self.metrics.total_tasks,
            self.metrics.passed_tasks,
            self.metrics.failed_tasks,
            self.metrics.pass_rate * 100.0,
            self.metrics.avg_latency_ms,
            self.metrics.total_tokens_input + self.metrics.total_tokens_output,
            self.metrics.total_cost_usd,
            rows
        )
    }
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
